name: Deploy Flask App

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-echo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Echo hello
        run: echo "CI/CD pipeline test successful"
